### ISSUE TITLE
Publish version 0.7.1 to npm

### ISSUE THREAD

**Issue by ggrossetie** [anthonny/opal-npm-wrapper#5]
Could you please publish the 0.7.1 version to npm. I though this was done automatically but I can't find the version: https://registry.npmjs.org/opal-npm-wrapper/0.7.1

``` json
{
"error": "version not found: 0.7.1"
}
```

**Comment by anthonny** [comment]
Done, but i made a mistake after the merge of your PR, my bad.
The tag 0.7.0 and 0.7.1 didn't work because of this new control in the opal source : 

``` javascript
  if (typeof(this.Opal) !== 'undefined') {
    console.warn('Opal already loaded. Loading twice can cause troubles, please fix your setup.');
    return this.Opal;
  }
```

Now there a test with Mocha.

I have created a 0.7.1-1 because i can't republish an old version on npm
https://registry.npmjs.org/opal-npm-wrapper/0.7.1-1

**Comment by ggrossetie** [comment]
Thanks, that's fine :smile: 
I guess only you can publish a new version ?
